title: xTools4 user documentation
email: gustavo@hipertipo.com
description: xTools4 user documentation
baseurl: ""
url: https://gferreira.github.io/xTools4

collections:
  reference:
    output: true
    permalink: /:path/
  topics:
    output: true
    permalink: /:path/

markdown: kramdown

version: 0.6.5

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

jekyll_tidy:
  exclude: []
  # ignore_env: development
  compress_html: false
